### ISSUE TITLE
Nub question

### ISSUE THREAD

**Issue by PipeDeveloper** [SR2k/block-storm#2]
Can you write a readme how to use?
How to add your wallet and see statistics?

Thanks in advance

**Comment by SR2k** [comment]
Hi, I've added a wiki page, see https://github.com/SR2k/supportxmr-dashboard/wiki/Usage

**Comment by PipeDeveloper** [comment]
@SR2k ohh i see, only works on the phone hahaha
I tried to oppen on my laptop using google chrome, mozilla and edge but it doesnt worked.

Very nice work!, next step is to make it work on computers 👍

**Comment by SR2k** [comment]
@PipeDeveloper Thanks! 
And it should work... at least works on my Chrome, Firefox and Edge.
Try add the site into your content blockers' white list (like minerBlock and AdBlock Plus).

**Comment by SR2k** [comment]
@PipeDeveloper I have added a message popup bubble to tell users about this

**Comment by PipeDeveloper** [comment]
Solved, it was my antivirus (im using norton)
Nice work! close.
